name: Auto Update WARP in WARP

on:
  schedule:
    - cron: '0 * * * *'   # Runs every hour
  workflow_dispatch:        # Manual trigger

jobs:
  update_warp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard-tools curl jq fping
          curl -fsSL https://pkg.cloudflarewarp.com/cloudflare-warp.asc | sudo tee /etc/apt/trusted.gpg.d/cloudflare-warp.asc
          echo "deb https://pkg.cloudflarewarp.com/ /" | sudo tee /etc/apt/sources.list.d/cloudflare-warp.list
          sudo apt-get update
          sudo apt-get install -y cloudflare-warp

      - name: Download and Install WARP-GO
        run: |
          wget -O install-warp.sh https://raw.githubusercontent.com/Ptechgithub/warp/main/endip/install.sh
          chmod +x install-warp.sh
          sudo ./install-warp.sh

      - name: Ensure Scripts Are Downloaded & Executable
        run: |
          mkdir -p ./scripts
          
          for script in warp-go.sh ipv6-scan.sh update-ip-port.py; do
            if [ ! -f ./scripts/$script ]; then
              echo "⚠️ $script not found! Downloading..."
              wget -O ./scripts/$script https://raw.githubusercontent.com/Ptechgithub/warp/main/scripts/$script
            fi
          done
          
          chmod +x ./scripts/*.sh || echo "⚠️ No executable files found!"

      - name: Run WARP Setup (First Layer)
        run: |
          echo "✔️ Running warp-go.sh (First Layer)..."
          for i in {1..3}; do
            echo "2" | bash ./scripts/warp-go.sh && break || echo "❌ warp-go.sh failed! Retrying ($i)..."
            sleep 5
          done

      - name: Run WARP Setup (Second Layer - WARP in WARP)
        run: |
          echo "✔️ Running warp-go.sh (Second Layer - WARP in WARP)..."
          for i in {1..3}; do
            echo "2" | bash ./scripts/warp-go.sh && break || echo "❌ warp-go.sh failed! Retrying ($i)..."
            sleep 5
          done

      - name: Run IPv6 Scanner
        run: |
          echo "✔️ Running ipv6-scan.sh..."
          for i in {1..3}; do
            bash ./scripts/ipv6-scan.sh && break || echo "❌ ipv6-scan.sh failed! Retrying ($i)..."
            sleep 5
          done

      - name: Update Hiddify Config
        run: |
          echo "✔️ Running update-ip-port.py..."
          for i in {1..3}; do
            python3 ./scripts/update-ip-port.py && break || echo "❌ update-ip-port.py failed! Retrying ($i)..."
            sleep 5
          done

      - name: Commit and Push Changes
        run: |
          git add hiddify-config.json || echo "⚠️ No files to update."
          git diff --cached --quiet || git commit -m "🔄 Auto-update fastest WARP in WARP IPv6"
          git push || echo "⚠️ Failed to push changes."

      - name: Auto-Restart on Failure
        if: failure()
        run: |
          echo "❌ Workflow failed! Restarting..."
          gh workflow run warp-in-warp.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}